NJnaiduportal/urls.py
from django.contrib import admin
from django.urls import path, include
from NJnaiduapp  import urls
from adminapp import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('site/', include('NJnaiduapp.urls')),
    path('site-admin/', include('adminapp.urls')),
    path('summernote/', include('django_summernote.urls')),
]

adminapp/urls.py
from django.contrib import admin
from django.urls import path
from adminapp import views
from django.conf import settings
from django.conf.urls.static import static  

urlpatterns = [
    path('', views.login, name='login'),
    path('dashboard', views.dashboard, name='dashboard'),


    ###########  Signup  ###############

    path('signup_create', views.signup_create, name='signup_create'),
    path('signup_list', views.signup_list, name='signup_list'),
    path('signup_edit/<int:pk>', views.signup_edit, name='signup_edit'),
    path('signup_delete/<int:pk>', views.signup_delete, name='signup_delete'),

    ########## LOGIN #################

    path('logout', views.logout, name='logout'),
    path('forget_password', views.forget_password, name='forget_password'),
    path('otp', views.otp, name='otp'),
    path('set_password', views.set_password, name='set_password'),

    ###############  ITEM ##########

    path('item_create', views.item_create, name='item_create'),
    path('item_list', views.item_list, name='item_list'),
    path('item_view/<int:pk>', views.item_view, name='item_view'),
    path('item_edit/<int:pk>', views.item_edit, name='item_edit'),
    path('item_delete/<int:pk>', views.item_delete, name='item_delete'),
    path('contact', views.contact, name = 'contact'),


    ###############  Category ##########

    path('category_create', views.category_create, name='category_create'),
    path('category_view/<int:pk>', views.category_view, name='category_view'),
    path('category_list', views.category_list, name='category_list'),
    path('category_edit/<int:pk>', views.category_edit, name='category_edit'),
    path('category_delete/<int:pk>', views.category_delete, name='category_delete'),


    ###############  Section1 ##########

    path('sec1_create', views.sec1_create, name='sec1_create'),
    path('sec1_view/<int:pk>', views.sec1_view, name='sec1_view'),
    path('sec1_list', views.sec1_list, name='sec1_list'),
    path('sec1_edit/<int:pk>', views.sec1_edit, name='sec1_edit'),
    path('sec1_delete/<int:pk>', views.sec1_delete, name='sec1_delete'),

    ###############  Section2 ##########

    path('sec2_create', views.sec2_create, name='sec2_create'),
    path('sec2_view/<int:pk>', views.sec2_view, name='sec2_view'),
    path('sec2_list', views.sec2_list, name='sec2_list'),
    path('sec2_edit/<int:pk>', views.sec2_edit, name='sec2_edit'),
    path('sec2_delete/<int:pk>', views.sec2_delete, name='sec2_delete'),
   

   
    ###############   Why Us ##########

    path('whyus_create', views.whyus_create, name='whyus_create'),
    path('whyus_view/<int:pk>', views.whyus_view, name='whyus_view'),
    path('whyus_list', views.whyus_list, name='whyus_list'),
    path('whyus_edit/<int:pk>', views.whyus_edit, name='whyus_edit'),
    path('whyus_delete/<int:pk>', views.whyus_delete, name='whyus_delete'),

     ###############  Our TEAM ##########

    path('ourteam_create', views.ourteam_create, name='ourteam_create'),
    path('ourteam_view/<int:pk>', views.ourteam_view, name='ourteam_view'),
    path('ourteam_list', views.ourteam_list, name='ourteam_list'),
    path('ourteam_edit/<int:pk>', views.ourteam_edit, name='ourteam_edit'),
    path('ourteam_delete/<int:pk>', views.ourteam_delete, name='ourteam_delete'),

     ###############  Specialities ##########

    path('specialities_create', views.specialities_create, name='specialities_create'),
    path('specialities_view/<int:pk>', views.specialities_view, name='specialities_view'),
    path('specialities_list', views.specialities_list, name='specialities_list'),
    path('specialities_edit/<int:pk>', views.specialities_edit, name='specialities_edit'),
    path('specialities_delete/<int:pk>', views.specialities_delete, name='specialities_delete'),

     ###############  Procedure ##########

    path('procedure_create', views.procedure_create, name='procedure_create'),
    path('procedure_view/<int:pk>', views.procedure_view, name='procedure_view'),
    path('procedure_list', views.procedure_list, name='procedure_list'),
    path('procedure_edit/<int:pk>', views.procedure_edit, name='procedure_edit'),
    path('procedure_delete/<int:pk>', views.procedure_delete, name='procedure_delete'),

     ###############  Event ##########

    path('event_create', views.event_create, name='event_create'),
    path('event_view/<int:pk>', views.event_view, name='event_view'),
    path('event_list', views.event_list, name='event_list'),
    path('event_edit/<int:pk>', views.event_edit, name='event_edit'),
    path('event_delete/<int:pk>', views.event_delete, name='event_delete'),

     ###############  Images ##########

    path('image_create', views.image_create, name='image_create'),
    path('image_view/<int:pk>', views.image_view, name='image_view'),
    path('image_list', views.image_list, name='image_list'),
    path('image_edit/<int:pk>', views.image_edit, name='image_edit'),
    path('image_delete/<int:pk>', views.image_delete, name='image_delete'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

NJnaiduapp/models.py
from django.db import models
from django.utils import timezone
from django.template.defaultfilters import slugify

class User(models.Model):
    user_name = models.CharField(
        max_length=50, unique=True, null=True, blank=True)
    dateofbirth = models.DateField(null=True, blank=True)
    email = models.EmailField(null=True, blank=True,unique=True)
    mobile_number = models.CharField(max_length=15, null=True, blank=True)
    password = models.CharField(max_length=200, null=True, blank=True)
    address_line_1 = models.CharField(max_length=200, null=True, blank=True)
    address_line_2 = models.CharField(max_length=200, null=True, blank=True)
    status = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    remarks = models.CharField(max_length=200, null=True, blank=True)
    user_image = models.ImageField(upload_to='media', blank=True, null=True)
    active_from = models.DateTimeField(
        default=timezone.now, blank=True, null=True)
    active_to = models.DateTimeField(blank=True, null=True)
    last_login = models.DateTimeField(default=timezone.now, editable=False)
    last_ip_address=models.CharField(max_length=50,null=True,blank=True)

    # Relationship Fields
    created_user = models.ForeignKey('User', on_delete=models.CASCADE, related_name='user_c_user',
                                     null=True, blank=True)
    modified_user = models.ForeignKey('User', on_delete=models.CASCADE, related_name='user_m_user',
                                      null=True, blank=True)



    def __str__(self):
        return str(self.user_name)


class Item(models.Model):
    item_name = models.CharField(max_length=200,null=True,blank=True)
    slug = models.SlugField(max_length = 250, null = True, blank = True) 
    description=models.TextField(null=True,blank=True)
    item_image = models.ImageField(upload_to='itemimage', blank=True, null=True)
    meta_tag = models.CharField(max_length=30,null=True,blank=True)
    meta_title = models.CharField(max_length=200,null=True,blank=True)
    meta_description = models.CharField(max_length=200,null=True,blank=True)
    meta_keywords = models.CharField(max_length=200,null=True,blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    active_from = models.DateTimeField(
        default=timezone.now, blank=True, null=True)
    active_to = models.DateTimeField(blank=True, null=True)
    status = models.BooleanField(default=True)
    
    # Relationship Fields
    created_user = models.ForeignKey('User', on_delete=models.CASCADE, related_name='item_c_user',
                                     null=True, blank=True)
    modified_user = models.ForeignKey('User', on_delete=models.CASCADE, related_name='item_m_user',
                                      null=True, blank=True)

    
    def __str__(self):
        return str(self.item_name)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.item_name)
        super(Item, self).save(*args, **kwargs)


class Category(models.Model):
    category_name = models.CharField(max_length=200,null=True,blank=True)
    slug = models.SlugField(max_length = 250, null = True, blank = True) 
    category_description=models.TextField(null=True,blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    active_from = models.DateTimeField(
        default=timezone.now, blank=True, null=True)
    active_to = models.DateTimeField(blank=True, null=True)
    status = models.BooleanField(default=True)
    
    # Relationship Fields
    item= models.ManyToManyField('Item',null=True,blank=True)
    created_user = models.ForeignKey('User', on_delete=models.CASCADE, related_name='category_c_user',
                                     null=True, blank=True)
    modified_user = models.ForeignKey('User', on_delete=models.CASCADE, related_name='category_m_user',
                                      null=True, blank=True)
    

    def __str__(self):
        return str(self.category_name)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.category_name)
        super(Category, self).save(*args, **kwargs)


class Section1(models.Model):
    title = models.CharField(max_length=200,null=True,blank=True)
    description = models.TextField()
    section_image = models.ImageField(upload_to='section1', blank=True, null=True)
    mobile_number=models.CharField(max_length=15, null=True, blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    active_from = models.DateTimeField(
        default=timezone.now, blank=True, null=True)
    active_to = models.DateTimeField(blank=True, null=True)
    status = models.BooleanField(default=True)
    
    # Relationship Fields
    created_user = models.ForeignKey('User', on_delete=models.CASCADE, related_name='section1_c_user',
                                     null=True, blank=True)
    modified_user = models.ForeignKey('User', on_delete=models.CASCADE, related_name='section1_m_user',
                                      null=True, blank=True)
    


    def __str__(self):
        return str(self.title)

class Section2(models.Model):
    title = models.CharField(max_length=200,null=True,blank=True)
    description =models.TextField()
    section2_image = models.ImageField(upload_to='section2', blank=True, null=True)
    section2background_image = models.ImageField(upload_to='section2back', blank=True, null=True)
    happy_patients=models.IntegerField(default='0',null=True,blank=True)
    surgeries=models.IntegerField(default='0',null=True,blank=True)
    doctors=models.IntegerField(default='0',null=True,blank=True)
    clinics=models.IntegerField(default='0',null=True,blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    active_from = models.DateTimeField(
        default=timezone.now, blank=True, null=True)
    active_to = models.DateTimeField(blank=True, null=True)
    status = models.BooleanField(default=True)
    
    # Relationship Fields
    created_user = models.ForeignKey('User', on_delete=models.CASCADE, related_name='section2_c_user',
                                     null=True, blank=True)
    modified_user = models.ForeignKey('User', on_delete=models.CASCADE, related_name='section2_m_user',
                                      null=True, blank=True)
    


    def __str__(self):
        return str(self.title)



class WhyUs(models.Model):
    title = models.CharField(max_length=200,null=True,blank=True)
    description =models.TextField()
    icon=models.CharField(max_length=200,null=True,blank=True)
    iconcolour=models.CharField(max_length=200,null=True,blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    active_from = models.DateTimeField(
        default=timezone.now, blank=True, null=True)
    active_to = models.DateTimeField(blank=True, null=True)
    status = models.BooleanField(default=True)
    
    # Relationship Fields
    created_user = models.ForeignKey('User', on_delete=models.CASCADE, related_name='whyus_c_user',
                                     null=True, blank=True)
    modified_user = models.ForeignKey('User', on_delete=models.CASCADE, related_name='whyus_m_user',
                                      null=True, blank=True)


    def __str__(self):
        return str(self.title)




class Procedure(models.Model):
    procedure_name = models.CharField(max_length=200,null=True,blank=True)
    procedure_description= models.TextField()
    slug = models.SlugField(max_length = 250, null = True, blank = True) 
    image = models.ImageField(upload_to='procedure', blank=True, null=True)
    meta_tag = models.CharField(max_length=30,null=True,blank=True)
    meta_title = models.CharField(max_length=200,null=True,blank=True)
    meta_description = models.CharField(max_length=200,null=True,blank=True)
    meta_keywords = models.CharField(max_length=200,null=True,blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    active_from = models.DateTimeField(
        default=timezone.now, blank=True, null=True)
    active_to = models.DateTimeField(blank=True, null=True)
    status = models.BooleanField(default=True)

    # Relationship Fields
    created_user = models.ForeignKey('User', on_delete=models.CASCADE, related_name='procedure_c_user',
                                     null=True, blank=True)
    modified_user = models.ForeignKey('User', on_delete=models.CASCADE, related_name='procedure_m_user',
                                      null=True, blank=True)
        


    def __str__(self):
        return str(self.procedure_name)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.procedure_name)
        super(Procedure, self).save(*args, **kwargs)

class Specialities(models.Model):
    speciality_name = models.CharField(max_length=200,null=True,blank=True)
    speciality_description= models.TextField()
    slug = models.SlugField(max_length = 250, null = True, blank = True) 
    image = models.ImageField(upload_to='specialities', blank=True, null=True)
    meta_tag = models.CharField(max_length=30,null=True,blank=True)
    meta_title = models.CharField(max_length=200,null=True,blank=True)
    meta_description = models.CharField(max_length=200,null=True,blank=True)
    meta_keywords = models.CharField(max_length=200,null=True,blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    active_from = models.DateTimeField(
        default=timezone.now, blank=True, null=True)

adminapp/models.py
from django.db import models

# Create your models here.

adminapp/templates/Specialities/specialities-create.html
{% extends 'User/index.html' %}
{% block content %}
<style>
    iframe.note-fullscreen {
        position: fixed;
        top: 0;
        left: 0;
        width: 100vw !important;
        height: 100vh !important;
        z-index: 4000;
    }
</style>



<div id="main-wrapper">


    <div class="page-wrapper">

        <div class="row page-titles">
            <div class="col-md-5 align-self-center">
                <h3 class="text-themecolor">Speciality create</h3>
            </div>
            <div class="col-md-7 align-self-center">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url 'dashboard' %}">Home</a></li>
                    <li class="breadcrumb-item"><a href="{% url 'specialities_create' %}">Speciality create</a></li>
                </ol>
            </div>
            <div class="">
                <button
                    class="right-side-toggle waves-effect waves-light btn-inverse btn btn-circle btn-sm pull-right m-l-10"><i
                        class="ti-settings text-white"></i></button>
            </div>
        </div>
        <div class="container-fluid">



            <!-- {{ form.as_p }} -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="card card-outline-info">
                        <div class="card-header">
                            <h4 class="m-b-0 text-white">Speciality Create</h4>
                        </div>
                        <div class="card-body">
                            <form method="POST">
                                {% csrf_token %}
                                <div class=" form-body">
                                    <div class="col-md-12">
                                        <h4>Speciality Description</h4>
                                        <div class="col-md-12 form-group row">
                                           
                                            <div class="col-md-9">
                                                <textarea name="description" required
                                                cols="40" id="id_description" rows="5" class="form-control"></textarea>
                                            </div>
                                            <div class="clearfix"></div>
                                        </div> 
                                        <div class=" summernote-div" cols="40" rows="10"
                                            summernote="{&#39;height&#39;: &#39;400px&#39;, &#39;width&#39;: &#39;50%&#39;}"
                                            width="100%" height="400px">
                                            <iframe id="id_description_iframe" src="/summernote/editor/id_description/"
                                                frameborder="0" width="100%" height="400px"></iframe>
                                        </div>
                                    </div><br>
                                    <div class="col-md-12 form-group row">
                                        <label for="id_speciality_name"
                                            class="control-label text-right col-md-3">Speciality name:</label>
                                        <div class="col-md-9">
                                            <input type="text" name="speciality_name" value="{{book.speciality_name}}" id="id_speciality_name"
                                                maxlength="200" class="form-control">

                                        </div>
                                    </div>
                                    <div class="col-md-12 form-group row">
                                        <label for="id_meta_tag"
                                            class="control-label text-right col-md-3">Meta tag:</label>
                                        <div class="col-md-9">
                                            <input type="text" name="meta_tag" id="id_meta_tag" value="{{book.meta_tag}}" maxlength="30" class="form-control">

                                        </div>
                                    </div>
                                    <div class="col-md-12 form-group row">
                                        <label for="id_meta_title"
                                            class="control-label text-right col-md-3">Meta title:</label>
                                        <div class="col-md-9">
                                            <input type="text"  name="meta_title" id="id_meta_title" value="{{book.meta_title}}" maxlength="200" class="form-control">

                                        </div>
                                    </div>
                                    <div class="col-md-12 form-group row">
                                        <label for="id_meta_description"
                                            class="control-label text-right col-md-3">Meta description:</label>
                                        <div class="col-md-9">
                                            <textarea type="text"  name="meta_description"  id="meta_description" maxlength="200" class="form-control">{{book.meta_description}}</textarea>

                                        </div>
                                    </div>
                                    <div class="col-md-12 form-group row">
                                        <label for="id_meta_keywords"
                                            class="control-label text-right col-md-3">Meta keywords:</label>
                                        <div class="col-md-9">
                                            <input type="text" name="meta_keywords" id="id_meta_keywords" value="{{book.meta_keywords}}" maxlength="200" class="form-control">

                                        </div>
                                    </div>

                                    <div class="form-group row ">
                                        <label 
                                            class="control-label text-right col-md-3">Status</label>
                                        <div class="col-sm-9">
                                            <div class="m-b-10">
                                                <label class="custom-control custom-checkbox">
                                                    <input type="checkbox" name="on" class="custom-control-input" {% if book.status %} checked {% else %} unchecked {% endif %}  >
                                                    <span class="custom-control-label"></span>
                                                </label>
                                            </div>


                                        </div>

                                    </div>
                                 
                                    <!-- <div class="col-md-12 form-group row">
                                                <label for="id_description" class="control-label text-right col-md-3">Description:</label>
                                                <div class="col-md-9">
                                                    <textarea name="description" required
                                                    cols="40" id="id_description" rows="5" class="form-control"></textarea>
                                                </div>
                                                <div class="clearfix"></div>
                                            </div> -->

                                    <div class="row col-md-12 form-group row">
                                        <div class="col-md-12">
                                            <input type="submit" class="btn btn-success pull-right" value="Submit" />
                                        </div>
                                    </div>




                            </form>
                        </div>
                    </div>
                </div>
            </div>

            <!-- <input type="submit" value="Submit" /> -->


        </div>



    </div>

</div>
</div>
<script>
    var settings_id_description = { "toolbar": [["style", ["style"]], ["font", ["bold", "italic", "underline", "superscript", "subscript", "strikethrough", "clear"]], ["fontname", ["fontname"]], ["fontsize", ["fontsize"]], ["color", ["color"]], ["para", ["ul", "ol", "paragraph"]], ["height", ["height"]], ["table", ["table"]], ["insert", ["link", "picture", "video", "hr"]], ["view", ["fullscreen", "codeview"]], ["help", ["help"]]], "height": "400px", "url": { "upload_attachment": "/summernote/upload_attachment/", "language": "/static/summernote/lang/summernote-en-US.min.js" }, "lang": "en-US", "width": "100%", "airMode": false };
</script>
{% endblock %}

adminapp/templates/Specialities/specialities-list.html
{% extends 'User/index.html' %}
{% block content %}
<div class="page-wrapper">
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h3 class="text-themecolor">Speciality List</h3>
        </div>
        <div class="col-md-7 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'dashboard' %}">Home</a></li>
                <li class="breadcrumb-item"><a href="{% url 'specialities_list' %}">Speciality List</a></li>
            </ol>
        </div>
        <div>
            <button
                class="right-side-toggle waves-effect waves-light btn-inverse btn btn-circle btn-sm pull-right m-l-10"><i
                    class="ti-settings text-white"></i></button>
        </div>
    </div>
    <div class="container-fluid">

        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Add & Remove Rows</h4>
                        <!-- <h6 class="card-subtitle">You can add or remove rows with Footable</h6> -->
                        <table id="demo-foo-addrow2" class="table table-bordered table-hover toggle-circle"
                            data-page-size="7">
                            <thead>
                                <tr>
                                    <th data-sort-initial="true" data-toggle="true"> Speciality name</th>
                                    <!-- <th>Speciality Description </th> -->
                                    <th>Meta tag</th>
                                    <th>Meta title</th>
                                    <th>Meta description</th>
                                    <th>Meta keywords</th>
                                    <th data-sort-ignore="true" class="min-width">Action</th>
                                </tr>
                            </thead>
                            <div class="m-t-40">
                                <div class="d-flex">
                                    <!-- <div class="mr-auto">
                                        <div class="form-group">
                                            <button id="demo-btn-addrow" class="btn btn-primary btn-sm"><i
                                                    class="icon wb-plus" aria-hidden="true"></i>Add New Row
                                            </button>
                                            <small>New row will be added in last page.</small> </div>
                                    </div> -->
                                    <div class="ml-auto">
                                        <div class="form-group">
                                            <input id="demo-input-search2" type="text" placeholder="Search"
                                                autocomplete="off">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <tbody>
                                {% for book in form %}
                                <tr>
                                    <td>{{ book.speciality_name }}</td>
                                    <!-- <td>{{ book.speciality_description }}</td> -->
                                    <td>{{book.meta_tag}}</td>
                                    <td>{{book.meta_title}}</td>
                                    <td>{{book.meta_description}}</td>
                                    <td>{{book.meta_keywords}}</td>
                                    <td>
                                        <button type="button"
                                            class="btn btn-sm btn-icon btn-pure btn-outline delete-row-btn"
                                            data-toggle="tooltip" data-original-title="Delete"><a
                                                href="{% url 'specialities_edit' book.id %}"><i class="ti-close"
                                                    aria-hidden="true"></i></a></button>
                                        <button type="button"
                                            class="btn btn-sm btn-icon btn-pure btn-outline delete-row-btn"
                                            data-toggle="tooltip" data-original-title="Delete"><a
                                                href="{% url 'specialities_delete' book.id %}"><i class="ti-trash"
                                                    aria-hidden="true"></i></a></button>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>

                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}