NJnaiduportal/urls.py
from django.contrib import admin
from django.urls import path, include
from NJnaiduapp  import urls
from adminapp import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('site/', include('NJnaiduapp.urls')),
    path('site-admin/', include('adminapp.urls')),
    path('summernote/', include('django_summernote.urls')),
]

adminapp/urls.py
from django.contrib import admin
from django.urls import path
from adminapp import views
from django.conf import settings
from django.conf.urls.static import static  

urlpatterns = [
    path('', views.login, name='login'),
    path('dashboard', views.dashboard, name='dashboard'),


    ###########  Signup  ###############

    path('signup_create', views.signup_create, name='signup_create'),
    path('signup_list', views.signup_list, name='signup_list'),
    path('signup_edit/<int:pk>', views.signup_edit, name='signup_edit'),
    path('signup_delete/<int:pk>', views.signup_delete, name='signup_delete'),

    ########## LOGIN #################

    path('logout', views.logout, name='logout'),
    path('forget_password', views.forget_password, name='forget_password'),
    path('otp', views.otp, name='otp'),
    path('set_password', views.set_password, name='set_password'),

    ###############  ITEM ##########

    path('item_create', views.item_create, name='item_create'),
    path('item_list', views.item_list, name='item_list'),
    path('item_view/<int:pk>', views.item_view, name='item_view'),
    path('item_edit/<int:pk>', views.item_edit, name='item_edit'),
    path('item_delete/<int:pk>', views.item_delete, name='item_delete'),
    path('contact', views.contact, name = 'contact'),


    ###############  Category ##########

    path('category_create', views.category_create, name='category_create'),
    path('category_view/<int:pk>', views.category_view, name='category_view'),
    path('category_list', views.category_list, name='category_list'),
    path('category_edit/<int:pk>', views.category_edit, name='category_edit'),
    path('category_delete/<int:pk>', views.category_delete, name='category_delete'),


    ###############  Section1 ##########

    path('sec1_create', views.sec1_create, name='sec1_create'),
    path('sec1_view/<int:pk>', views.sec1_view, name='sec1_view'),
    path('sec1_list', views.sec1_list, name='sec1_list'),
    path('sec1_edit/<int:pk>', views.sec1_edit, name='sec1_edit'),
    path('sec1_delete/<int:pk>', views.sec1_delete, name='sec1_delete'),

    ###############  Section2 ##########

    path('sec2_create', views.sec2_create, name='sec2_create'),
    path('sec2_view/<int:pk>', views.sec2_view, name='sec2_view'),
    path('sec2_list', views.sec2_list, name='sec2_list'),
    path('sec2_edit/<int:pk>', views.sec2_edit, name='sec2_edit'),
    path('sec2_delete/<int:pk>', views.sec2_delete, name='sec2_delete'),
   

   
    ###############   Why Us ##########

    path('whyus_create', views.whyus_create, name='whyus_create'),
    path('whyus_view/<int:pk>', views.whyus_view, name='whyus_view'),
    path('whyus_list', views.whyus_list, name='whyus_list'),
    path('whyus_edit/<int:pk>', views.whyus_edit, name='whyus_edit'),
    path('whyus_delete/<int:pk>', views.whyus_delete, name='whyus_delete'),

     ###############  Our TEAM ##########

    path('ourteam_create', views.ourteam_create, name='ourteam_create'),
    path('ourteam_view/<int:pk>', views.ourteam_view, name='ourteam_view'),
    path('ourteam_list', views.ourteam_list, name='ourteam_list'),
    path('ourteam_edit/<int:pk>', views.ourteam_edit, name='ourteam_edit'),
    path('ourteam_delete/<int:pk>', views.ourteam_delete, name='ourteam_delete'),

     ###############  Specialities ##########

    path('specialities_create', views.specialities_create, name='specialities_create'),
    path('specialities_view/<int:pk>', views.specialities_view, name='specialities_view'),
    path('specialities_list', views.specialities_list, name='specialities_list'),
    path('specialities_edit/<int:pk>', views.specialities_edit, name='specialities_edit'),
    path('specialities_delete/<int:pk>', views.specialities_delete, name='specialities_delete'),

     ###############  Procedure ##########

    path('procedure_create', views.procedure_create, name='procedure_create'),
    path('procedure_view/<int:pk>', views.procedure_view, name='procedure_view'),
    path('procedure_list', views.procedure_list, name='procedure_list'),
    path('procedure_edit/<int:pk>', views.procedure_edit, name='procedure_edit'),
    path('procedure_delete/<int:pk>', views.procedure_delete, name='procedure_delete'),

     ###############  Event ##########

    path('event_create', views.event_create, name='event_create'),
    path('event_view/<int:pk>', views.event_view, name='event_view'),
    path('event_list', views.event_list, name='event_list'),
    path('event_edit/<int:pk>', views.event_edit, name='event_edit'),
    path('event_delete/<int:pk>', views.event_delete, name='event_delete'),

     ###############  Images ##########

    path('image_create', views.image_create, name='image_create'),
    path('image_view/<int:pk>', views.image_view, name='image_view'),
    path('image_list', views.image_list, name='image_list'),
    path('image_edit/<int:pk>', views.image_edit, name='image_edit'),
    path('image_delete/<int:pk>', views.image_delete, name='image_delete'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

NJnaiduapp/models.py
from django.db import models
from django.utils import timezone
from django.template.defaultfilters import slugify

class User(models.Model):
    user_name = models.CharField(
        max_length=50, unique=True, null=True, blank=True)
    dateofbirth = models.DateField(null=True, blank=True)
    email = models.EmailField(null=True, blank=True,unique=True)
    mobile_number = models.CharField(max_length=15, null=True, blank=True)
    password = models.CharField(max_length=200, null=True, blank=True)
    address_line_1 = models.CharField(max_length=200, null=True, blank=True)
    address_line_2 = models.CharField(max_length=200, null=True, blank=True)
    status = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    remarks = models.CharField(max_length=200, null=True, blank=True)
    user_image = models.ImageField(upload_to='media', blank=True, null=True)
    active_from = models.DateTimeField(
        default=timezone.now, blank=True, null=True)
    active_to = models.DateTimeField(blank=True, null=True)
    last_login = models.DateTimeField(default=timezone.now, editable=False)
    last_ip_address=models.CharField(max_length=50,null=True,blank=True)

    # Relationship Fields
    created_user = models.ForeignKey('User', on_delete=models.CASCADE, related_name='user_c_user',
                                     null=True, blank=True)
    modified_user = models.ForeignKey('User', on_delete=models.CASCADE, related_name='user_m_user',
                                      null=True, blank=True)



    def __str__(self):
        return str(self.user_name)


class Item(models.Model):
    item_name = models.CharField(max_length=200,null=True,blank=True)
    slug = models.SlugField(max_length = 250, null = True, blank = True) 
    description=models.TextField(null=True,blank=True)
    item_image = models.ImageField(upload_to='itemimage', blank=True, null=True)
    meta_tag = models.CharField(max_length=30,null=True,blank=True)
    meta_title = models.CharField(max_length=200,null=True,blank=True)
    meta_description = models.CharField(max_length=200,null=True,blank=True)
    meta_keywords = models.CharField(max_length=200,null=True,blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    active_from = models.DateTimeField(
        default=timezone.now, blank=True, null=True)
    active_to = models.DateTimeField(blank=True, null=True)
    status = models.BooleanField(default=True)
    
    # Relationship Fields
    created_user = models.ForeignKey('User', on_delete=models.CASCADE, related_name='item_c_user',
                                     null=True, blank=True)
    modified_user = models.ForeignKey('User', on_delete=models.CASCADE, related_name='item_m_user',
                                      null=True, blank=True)

    
    def __str__(self):
        return str(self.item_name)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.item_name)
        super(Item, self).save(*args, **kwargs)


class Category(models.Model):
    category_name = models.CharField(max_length=200,null=True,blank=True)
    slug = models.SlugField(max_length = 250, null = True, blank = True) 
    category_description=models.TextField(null=True,blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    active_from = models.DateTimeField(
        default=timezone.now, blank=True, null=True)
    active_to = models.DateTimeField(blank=True, null=True)
    status = models.BooleanField(default=True)
    
    # Relationship Fields
    item= models.ManyToManyField('Item',null=True,blank=True)
    created_user = models.ForeignKey('User', on_delete=models.CASCADE, related_name='category_c_user',
                                     null=True, blank=True)
    modified_user = models.ForeignKey('User', on_delete=models.CASCADE, related_name='category_m_user',
                                      null=True, blank=True)
    

    def __str__(self):
        return str(self.category_name)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.category_name)
        super(Category, self).save(*args, **kwargs)


class Section1(models.Model):
    title = models.CharField(max_length=200,null=True,blank=True)
    description = models.TextField()
    section_image = models.ImageField(upload_to='section1', blank=True, null=True)
    mobile_number=models.CharField(max_length=15, null=True, blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    active_from = models.DateTimeField(
        default=timezone.now, blank=True, null=True)
    active_to = models.DateTimeField(blank=True, null=True)
    status = models.BooleanField(default=True)
    
    # Relationship Fields
    created_user = models.ForeignKey('User', on_delete=models.CASCADE, related_name='section1_c_user',
                                     null=True, blank=True)
    modified_user = models.ForeignKey('User', on_delete=models.CASCADE, related_name='section1_m_user',
                                      null=True, blank=True)
    


    def __str__(self):
        return str(self.title)

class Section2(models.Model):
    title = models.CharField(max_length=200,null=True,blank=True)
    description =models.TextField()
    section2_image = models.ImageField(upload_to='section2', blank=True, null=True)
    section2background_image = models.ImageField(upload_to='section2back', blank=True, null=True)
    happy_patients=models.IntegerField(default='0',null=True,blank=True)
    surgeries=models.IntegerField(default='0',null=True,blank=True)
    doctors=models.IntegerField(default='0',null=True,blank=True)
    clinics=models.IntegerField(default='0',null=True,blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    active_from = models.DateTimeField(
        default=timezone.now, blank=True, null=True)
    active_to = models.DateTimeField(blank=True, null=True)
    status = models.BooleanField(default=True)
    
    # Relationship Fields
    created_user = models.ForeignKey('User', on_delete=models.CASCADE, related_name='section2_c_user',
                                     null=True, blank=True)
    modified_user = models.ForeignKey('User', on_delete=models.CASCADE, related_name='section2_m_user',
                                      null=True, blank=True)
    


    def __str__(self):
        return str(self.title)



class WhyUs(models.Model):
    title = models.CharField(max_length=200,null=True,blank=True)
    description =models.TextField()
    icon=models.CharField(max_length=200,null=True,blank=True)
    iconcolour=models.CharField(max_length=200,null=True,blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    active_from = models.DateTimeField(
        default=timezone.now, blank=True, null=True)
    active_to = models.DateTimeField(blank=True, null=True)
    status = models.BooleanField(default=True)
    
    # Relationship Fields
    created_user = models.ForeignKey('User', on_delete=models.CASCADE, related_name='whyus_c_user',
                                     null=True, blank=True)
    modified_user = models.ForeignKey('User', on_delete=models.CASCADE, related_name='whyus_m_user',
                                      null=True, blank=True)


    def __str__(self):
        return str(self.title)




class Procedure(models.Model):
    procedure_name = models.CharField(max_length=200,null=True,blank=True)
    procedure_description= models.TextField()
    slug = models.SlugField(max_length = 250, null = True, blank = True) 
    image = models.ImageField(upload_to='procedure', blank=True, null=True)
    meta_tag = models.CharField(max_length=30,null=True,blank=True)
    meta_title = models.CharField(max_length=200,null=True,blank=True)
    meta_description = models.CharField(max_length=200,null=True,blank=True)
    meta_keywords = models.CharField(max_length=200,null=True,blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    active_from = models.DateTimeField(
        default=timezone.now, blank=True, null=True)
    active_to = models.DateTimeField(blank=True, null=True)
    status = models.BooleanField(default=True)

    # Relationship Fields
    created_user = models.ForeignKey('User', on_delete=models.CASCADE, related_name='procedure_c_user',
                                     null=True, blank=True)
    modified_user = models.ForeignKey('User', on_delete=models.CASCADE, related_name='procedure_m_user',
                                      null=True, blank=True)
        


    def __str__(self):
        return str(self.procedure_name)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.procedure_name)
        super(Procedure, self).save(*args, **kwargs)

class Specialities(models.Model):
    speciality_name = models.CharField(max_length=200,null=True,blank=True)
    speciality_description= models.TextField()
    slug = models.SlugField(max_length = 250, null = True, blank = True) 
    image = models.ImageField(upload_to='specialities', blank=True, null=True)
    meta_tag = models.CharField(max_length=30,null=True,blank=True)
    meta_title = models.CharField(max_length=200,null=True,blank=True)
    meta_description = models.CharField(max_length=200,null=True,blank=True)
    meta_keywords = models.CharField(max_length=200,null=True,blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    active_from = models.DateTimeField(
        default=timezone.now, blank=True, null=True)

adminapp/models.py
from django.db import models

# Create your models here.

adminapp/templates/User/forget-password.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'dashapp/assets/images/favicon.png' %}">
    <title>Admin Press Admin Template - The Ultimate Bootstrap 4 Admin Template</title>
    <!-- Bootstrap Core CSS -->
    <link href="{% static 'dashapp/assets/plugins/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="{% static 'dashapp/assets/css/style.css' %}" rel="stylesheet">
    <!-- You can change the theme colors from here -->
    <link href="{% static 'dashapp/assets/css/colors/blue.css' %}" id="theme" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js' %} IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js' %} doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js' %}"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js' %}/1.4.2/respond.min.js' %}"></script>
<![endif]-->
</head>

<body>

<!-- <form method="POST">
    {% csrf_token %}
    {% if messages %}
    {% for msg in messages %}
    <p style="color:red">{{msg}}</p>
    {% endfor %}
    {% endif %} 
<p><label>Email:</label> <input type="text" name="email" maxlength="50"></p>
<input class='btn btn-primary' type="submit"  value="submit">

</form> -->

<section id="wrapper">
    <div class="login-register" style="background-image:url({% static 'dashapp/assets/images/background/login-register.jpg' %});">
        <div class="login-box card">
            <div class="card-body">
                <form method="POST">
                    {% csrf_token %}
                <form class="form-horizontal" id="recoverform" action="http://themedesigner.in/demo/admin-press/main/index.html">
                    <div class="form-group ">
                        <div class="col-xs-12">
                            <h3>Recover Password</h3>
                            <p class="text-muted">Enter your Email and instructions will be sent to you! </p>
                        </div>
                    </div>
                    <div class="form-group ">
                        <div class="col-xs-12">
                            <input class="form-control" type="text" name="email" required="" placeholder="Email"> </div>
                    </div>
                    <div class="form-group text-center m-t-20">
                        <div class="col-xs-12">
                            <button class="btn btn-primary btn-lg btn-block text-uppercase waves-effect waves-light" type="submit">Reset</button>
                        </div>
                    </div>
                </form>
</form>
                </div>
                </div>
                </div>
                </section>

                  <!-- ============================================================== -->
    <!-- End Wrapper -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- All Jquery -->
    <!-- ============================================================== -->
    <script src="{% static 'dashapp/assets/plugins/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src="{% static 'dashapp/assets/plugins/bootstrap/js/popper.min.html"></script>
    <script src="{% static 'dashapp/assets/plugins/bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- slimscrollbar scrollbar JavaScript -->
    <script src="{% static 'dashapp/assets/js/jquery.slimscroll.js' %}"></script>
    <!--Wave Effects -->
    <script src="{% static 'dashapp/assets/js/waves.js' %}"></script>
    <!--Menu sidebar -->
    <script src="{% static 'dashapp/assets/js/sidebarmenu.js' %}"></script>
    <!--stickey kit -->
    <script src="{% static 'dashapp/assets/plugins/sticky-kit-master/dist/sticky-kit.min.js' %}"></script>
    <script src="{% static 'dashapp/assets/plugins/sparkline/jquery.sparkline.min.js' %}"></script>
    <!--Custom JavaScript -->
    <script src="{% static 'dashapp/assets/js/custom.min.js' %}"></script>
    <!-- ============================================================== -->
    <!-- Style switcher -->
    <!-- ============================================================== -->
    <script src="{% static 'dashapp/assets/plugins/styleswitcher/jQuery.style.switcher.js' %}"></script>
</body>
</html>

adminapp/templates/User/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'dashapp/assets/images/favicon.png' %}">
    <title>Admin Press Admin Template - The Ultimate Bootstrap 4 Admin Template</title>
    <!-- Bootstrap Core CSS -->
    <link href="{% static 'dashapp/assets/plugins/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="{% static 'dashapp/assets/css/style.css' %}" rel="stylesheet">
    <!-- You can change the theme colors from here -->
    <link href="{% static 'dashapp/assets/css/colors/blue.css' %}" id="theme" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js' %} IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js' %} doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js' %}"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js' %}/1.4.2/respond.min.js' %}"></script>
<![endif]-->
</head>

<body>
    
    <!-- ============================================================== -->
    <!-- Preloader - style you can find in spinners.css' %} -->
    <!-- ============================================================== -->
    <div class="preloader">
        <svg class="circular" viewBox="25 25 50 50">
            <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10" /> </svg>
    </div>
    <!-- ============================================================== -->
    <!-- Main wrapper - style you can find in pages.scss -->
    <!-- ============================================================== -->
    <section id="wrapper">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
        <div class="login-register" style="background-image:url({% static 'dashapp/assets/images/background/login-register.jpg' %});">
            <div class="login-box card">
                <div class="card-body">
                    <form class="form-horizontal form-material" id="loginform" action="#">
                        <h3 class="box-title m-b-20">Sign In</h3>
                        <div class="form-group ">
                            <div class="col-xs-12">
                                <input class="form-control" name="email" type="text" required="" placeholder="Email"> </div>
                        </div>
                        <div class="form-group">
                            <div class="col-xs-12">
                                <input class="form-control" name="password" type="password" required="" placeholder="Password"> </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-md-12 font-14">
                                <div class="checkbox checkbox-primary pull-left p-t-0">
                                    <input id="checkbox-signup" type="checkbox">
                                    <label for="checkbox-signup"> Remember me </label>
                                </div> <a href="{% url 'forget_password' %}" id="to-recover" class="text-dark pull-right"><!-- <i class="fa fa-lock m-r-5"></i> --> Forgot pwd?</a> </div>
                        </div>
                        <div class="form-group text-center m-t-20">
                            <div class="col-xs-12">
                                <button class="btn btn-info btn-lg btn-block text-uppercase waves-effect waves-light" input type="submit" value="Submit">Log In</button>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12 col-sm-12 col-md-12 m-t-10 text-center">
                                <div class="social">
                                    <a href="javascript:void(0)" class="btn  btn-facebook" data-toggle="tooltip" title="Login with Facebook"> <i aria-hidden="true" class="fa fa-facebook"></i> </a>
                                    <a href="javascript:void(0)" class="btn btn-googleplus" data-toggle="tooltip" title="Login with Google"> <i aria-hidden="true" class="fa fa-google-plus"></i> </a>
                                </div>
                            </div>
                        </div>  
                    </form>
                  
                </div>
            </div>
        </div>
    </form>
    </section>
    <!-- ============================================================== -->
    <!-- End Wrapper -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- All Jquery -->
    <!-- ============================================================== -->
    <script src="{% static 'dashapp/assets/plugins/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src="{% static 'dashapp/assets/plugins/bootstrap/js/popper.min.html"></script>
    <script src="{% static 'dashapp/assets/plugins/bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- slimscrollbar scrollbar JavaScript -->
    <script src="{% static 'dashapp/assets/js/jquery.slimscroll.js' %}"></script>
    <!--Wave Effects -->
    <script src="{% static 'dashapp/assets/js/waves.js' %}"></script>
    <!--Menu sidebar -->
    <script src="{% static 'dashapp/assets/js/sidebarmenu.js' %}"></script>
    <!--stickey kit -->
    <script src="{% static 'dashapp/assets/plugins/sticky-kit-master/dist/sticky-kit.min.js' %}"></script>
    <script src="{% static 'dashapp/assets/plugins/sparkline/jquery.sparkline.min.js' %}"></script>
    <!--Custom JavaScript -->
    <script src="{% static 'dashapp/assets/js/custom.min.js' %}"></script>
    <!-- ============================================================== -->
    <!-- Style switcher -->
    <!-- ============================================================== -->
    <script src="{% static 'dashapp/assets/plugins/styleswitcher/jQuery.style.switcher.js' %}"></script>
</body>
</html>

adminapp/templates/User/otp.html
<h2 text-align ="center">OTP</h2>
<form method="post">
    {% csrf_token %}
    {% if messages %}
    {% for msg in messages %}
    <p style="color:red">{{msg}}</p>
    {% endfor %}
    {% endif %}
<p><label>OTP:</label> <input type="text" name="otp" maxlength="50"></p>
<input class='btn btn-primary' type="submit"  value="submit">
</form>

adminapp/templates/User/set-password.html
<form method="POST">
    {% csrf_token %}
    {% if messages %}
    {% for msg in messages %}
    <p style="color:red">{{msg}}</p>
    {% endfor %}
    {% endif %}
    <p><label>Password:</label> <input type="text" name="password" maxlength="50"></p>
    <p><label>confirm_password:</label> <input type="text" name="confirm_password" maxlength="50"></p>
<input class='btn btn-primary' type="submit"  value="submit">
</form> 

adminapp/templates/User/signup-create.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <p><label for="id_user_name">User name:</label> <input type="text" value="{{book.user_name}}" name="user_name" maxlength="50"
            id="id_user_name"></p>
    <p><label for="id_dateofbirth">Dateofbirth:</label> <input type="date" value="{{book.dateofbirth|date:'Y-m-d'}}" name="dateofbirth" id="id_dateofbirth"></p>
    <p><label for="id_email">Email:</label> <input type="email" value="{{book.email}}" name="email" maxlength="254" id="id_email"></p>
    <p><label for="id_mobile_number">Mobile number:</label> <input type="text" value="{{book.mobile_number}}" name="mobile_number" maxlength="15"
            id="id_mobile_number"></p>
    <p><label for="id_password">Password:</label> <input type="password" value="{{book.password}}" name="password" maxlength="200" id="id_password">
    </p>
    <p><label for="id_address_line_1">Address line 1:</label> <input type="text" value="{{book.address_line_1}}" name="address_line_1" maxlength="200"
            id="id_address_line_1"></p> 
    <p><label for="id_address_line_2">Address line 2:</label> <input type="text"  value="{{book.address_line_2}}" name="address_line_2" maxlength="200"
            id="id_address_line_2"></p>
    <p><label for="id_status">Status:</label> <input type="checkbox"  checked name="status" id="id_status"></p>
    <p><label for="id_user_image">User image:</label> <input type="file"  value="{{book.user_image.url}}" name="user_image" accept="image/*"
            id="id_user_image"></p>
    <input type="submit" value="Submit" />
</form>

adminapp/templates/User/signup-list.html
<table>
<thead>
    <th>user_name</th>
    <th>email</th>
    <th>mobile_number</th>
    <th>status</th>
    <th>Edit</th>
    <th>Delete</th>
</thead>
<tbody>
    {% for book in form %}
  
    <td>{{ book.user_name }}</td>
    <td>{{ book.email }}</td>
    <td>{{ book.mobile_number }}</td>
    <td>{{ book.status }}</td>
    <td><a href="{% url 'signup_edit' book.id %}">edit</a></td>
    <td><a href="{% url 'signup_delete' book.id %}">delete</a></td>
   
    {% endfor %}
</tbody>
</table>

adminapp/templates/User/user-detail.html
<!-- include summernote css/js-->
{% extends "base.html" %}
{% load static %}                                          
{% block content %}
<link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.3/summernote.css" rel="stylesheet">
<script src="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.3/summernote.js"></script>

       
        <div class="portfolio-page-block portfolio-page-style-three mrb-172">
            <div class="container">
                <!-- Content Row -->
                <div class="row">
                    <div class="section-header">
                        <p>{{  loki.description|safe  }}</p>
                        
                    </div>
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
                
          
        </div><!-- /.portfolio-page-block -->  
{% endblock %}